CREATE TABLE IF NOT EXISTS `client_instance_cooltimes` (
                                                           `id` int NOT NULL,
                                                           `name` varchar(255) NOT NULL,
    `race` text,
    `max_member_dark` int DEFAULT NULL,
    `can_enter_mentor` tinyint(1) DEFAULT NULL,
    `enter_min_level_dark` int DEFAULT NULL,
    `coolt_tbl_id` int DEFAULT NULL,
    `min_member_light` int DEFAULT NULL,
    `enter_min_level_light` int DEFAULT NULL,
    `coolt_sync_id` int DEFAULT NULL,
    `description` text,
    `max_member_light` int DEFAULT NULL,
    `client_level` int DEFAULT NULL,
    `min_member_dark` int DEFAULT NULL,
    `indun_grade` int DEFAULT NULL,
    `indun_type` text,
    `f2p_coolt_tbl_id` int DEFAULT NULL,
    `item_desc` text,
    `enter_max_level_light` int DEFAULT NULL,
    `enter_max_level_dark` int DEFAULT NULL,
    `share_max_member` int DEFAULT NULL,
    `alarm_unit_score` int DEFAULT NULL,
    `desc_hud` text,
    `luna_type` text,
    `warpoint_desc` text,
    `bonus_warpoint` text,
    `warpoint_title` text,
    `using_warpoint` text,
    `pc_kill_warpoint` text,
    `bonus_time` text,
    `intrusion_warpoint` text,
    `warpoint` text,
    `exit_world_1` text,
    `exit_world_2` text,
    `exit_alias_1` text,
    `exit_alias_2` text,
    PRIMARY KEY (`id`),
    KEY `name` (`name`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
COMMIT;