CREATE TABLE `client_achievement_action` (
  `id` int(3) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `title` text,
  `description` text,
  `active` int(1) DEFAULT NULL,
  `type` text,
  `maxprogress` int(4) DEFAULT NULL,
  `completecond` text,
  `gold` text,
  `exp` text,
  `ap` text,
  `gp` text,
  `completecond_tag` text,
  `target_type` text,
  `levelgap` int(4) DEFAULT NULL,
  `retrieve_item` text,
  `item_name` varchar(255) DEFAULT NULL,
  `item_amount` int(4) DEFAULT NULL,
  `item_name1` varchar(255) DEFAULT NULL,
  `item_amount1` int(4) DEFAULT NULL,
  `item_name2` varchar(255) DEFAULT NULL,
  `item_amount2` int(4) DEFAULT NULL,
  `item_name3` varchar(255) DEFAULT NULL,
  `item_amount3` int(4) DEFAULT NULL,
  `item_name4` varchar(255) DEFAULT NULL,
  `item_amount4` int(4) DEFAULT NULL,
  `item_name5` varchar(255) DEFAULT NULL,
  `item_amount5` int(4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
