CREATE TABLE `client_achievement` (
  `id` int(3) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `title` text,
  `description` text,
  `active` int(1) NOT NULL,
  `type` text,
  `repeats` text,
  `race` text,
  `minlevel` int(2) NOT NULL,
  `maxlevel` int(2) NOT NULL,
  `completecount` int(2) NOT NULL,
  `gold` text,
  `exp` text,
  `ap` text,
  `gp` text,
  `item_name` varchar(255) DEFAULT NULL,
  `item_amount` int(4) DEFAULT NULL,
  `item_name1` varchar(255) DEFAULT NULL,
  `item_amount1` int(4) DEFAULT NULL,
  `item_name2` varchar(255) DEFAULT NULL,
  `item_amount2` int(4) DEFAULT NULL,
  `item_name3` varchar(255) DEFAULT NULL,
  `item_amount3` int(4) DEFAULT NULL,
  `item_name4` varchar(255) DEFAULT NULL,
  `item_amount4` int(4) DEFAULT NULL,
  `item_name5` varchar(255) DEFAULT NULL,
  `item_amount5` int(4) DEFAULT NULL,
  `action` int(4) DEFAULT NULL,
  `action1` int(4) DEFAULT NULL,
  `action2` int(4) DEFAULT NULL,
  `action3` int(4) DEFAULT NULL,
  `action4` int(4) DEFAULT NULL,
  `action5` int(4) DEFAULT NULL,
  `action6` int(4) DEFAULT NULL,
  `action7` int(4) DEFAULT NULL,
  `action8` int(4) DEFAULT NULL,
  `action9` int(4) DEFAULT NULL,
  `action10` int(4) DEFAULT NULL,
  `action11` int(4) DEFAULT NULL,
  `action12` int(4) DEFAULT NULL,
  `action13` int(4) DEFAULT NULL,
  `action14` int(4) DEFAULT NULL,
  `action15` int(4) DEFAULT NULL,
  `action16` int(4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
