CREATE TABLE IF NOT EXISTS `client_achievement_events` (
                                                           `id` int NOT NULL,
                                                           `name` varchar(255) NOT NULL,
    `end_day` datetime DEFAULT NULL,
    `maxlevel` int DEFAULT NULL,
    `race` text,
    `completepoint` int DEFAULT NULL,
    `start_day` datetime DEFAULT NULL,
    `mission_id` int DEFAULT NULL,
    `active` tinyint(1) DEFAULT NULL,
    `minlevel` int DEFAULT NULL,
    `event_period` int DEFAULT NULL,
    `day` text,
    `event_section` text,
    `gold_1` int DEFAULT NULL,
    `completecount_1` int DEFAULT NULL,
    `exp_1` int DEFAULT NULL,
    `gp_1` int DEFAULT NULL,
    `ap_1` int DEFAULT NULL,
    `maxstage` int DEFAULT NULL,
    `completecount_2` int DEFAULT NULL,
    `ap_2` int DEFAULT NULL,
    `completecount_3` int DEFAULT NULL,
    `exp_2` int DEFAULT NULL,
    `maxrewardcount` int DEFAULT NULL,
    `ap_3` int DEFAULT NULL,
    `event_group` text,
    PRIMARY KEY (`id`),
    KEY `name` (`name`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
COMMIT;