CREATE TABLE `client_achievement_event` (
  `id` int(4) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `event_section` int(1) DEFAULT NULL,
  `active` int(1) DEFAULT NULL,
  `start_day` text,
  `end_day` text,
  `day` text,
  `event_period` text,
  `race` text,
  `minlevel` int(2) DEFAULT NULL,
  `maxlevel` int(2) DEFAULT NULL,
  `maxstage` int(2) DEFAULT NULL,
  `completecount_1` int(3) DEFAULT NULL,
  `gold_1` text,
  `exp_1` text,
  `ap_1` text,
  `gp_1` text,
  `completecount_2` int(3) DEFAULT NULL,
  `gold_2` text,
  `exp_2` text,
  `ap_2` text,
  `gp_2` text,
  `completecount_3` int(3) DEFAULT NULL,
  `mission_id` int(4) DEFAULT NULL,
  `completepoint` int(4) DEFAULT NULL,
  `maxrewardcount` int(4) DEFAULT NULL,
  `item_name_1` varchar(255) DEFAULT NULL,
  `item_amount_1` int(4) DEFAULT NULL,
  `item_name_2` varchar(255) DEFAULT NULL,
  `item_amount_2` int(4) DEFAULT NULL,
  `item_name_3` varchar(255) DEFAULT NULL,
  `item_amount_3` int(4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
