CREATE TABLE `client_toypets` (
  `id` int(15) NOT NULL,
  `name` varchar(255) NOT NULL,
  `pet_condition_reward` varchar(255) DEFAULT NULL,
  `bag` varchar(255) DEFAULT NULL,
  `cam_angle` text,
  `desc_long` varchar(255) DEFAULT NULL,
  `wing` text,
  `cam_pos` text,
  `ask_cute_desc` text,
  `art_org_speed_normal_run` text,
  `combat_reaction` text,
  `foot_mat` text,
  `ask_lone_desc` text,
  `dir` text,
  `icon_name` varchar(255) DEFAULT NULL,
  `attach_mesh_size` text,
  `customize_color` text,
  `iserect` text,
  `altitude` text,
  `color` text,
  `description` varchar(255) DEFAULT NULL,
  `scale` text,
  `target_sound` text,
  `art_org_move_speed_normal_walk` text,
  `mesh` text,
  `ui_color` text,
  `func_type_name1` varchar(50) DEFAULT NULL,
  `func_type_name2` varchar(50) DEFAULT NULL,
  `func_type2` varchar(10) DEFAULT NULL,
  `func_type1` varchar(10) DEFAULT NULL,
  `customize_attach` text,
  `enemy_alarm` tinyint(1) DEFAULT NULL,
  `ui_colors` text,
  `upper` text,
  `side` text,
  `front` text,
  PRIMARY KEY (`id`),
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
