CREATE TABLE `client_achievement_events` (
  `id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `end_day` text,
  `maxlevel` int DEFAULT NULL,
  `race` text,
  `completepoint` int DEFAULT NULL,
  `start_day` text,
  `mission_end_day` text,
  `mission_id` int DEFAULT NULL,
  `active` tinyint(1) DEFAULT NULL,
  `minlevel` int DEFAULT NULL,
  `event_period` int DEFAULT NULL,
  `day` text,
  `event_section` text,
  `gold_1` int DEFAULT NULL,
  `completecount_1` int DEFAULT NULL,
  `exp_1` int DEFAULT NULL,
  `gp_1` int DEFAULT NULL,
  `ap_1` int DEFAULT NULL,
  `maxstage` int DEFAULT NULL,
  `completecount_2` int DEFAULT NULL,
  `ap_2` int DEFAULT NULL,
  `completecount_3` int DEFAULT NULL,
  `item_list_1` text,
  `item_list_3` text,
  `exp_2` int DEFAULT NULL,
  `maxrewardcount` int DEFAULT NULL,
  `item_list_2` text,
  `ap_3` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
