
DROP TABLE IF EXISTS `client_housing_objects`;
CREATE TABLE IF NOT EXISTS `client_housing_objects` (
                                                        `id` int NOT NULL,
                                                        `name` varchar(255) NOT NULL,
    `description` text,
    `housing_size_tag` text,
    `type` text,
    `dir` text,
    `icon_name` text,
    `quality` text,
    `place_location` text,
    `place_area` text,
    `mesh` text,
    `housingobj_max_use_days` int DEFAULT NULL,
    `housingobj_function` text,
    `in_house_warehouse_idx` int DEFAULT NULL,
    `place_limit_tag` text,
    `cannot_changecolor` tinyint(1) DEFAULT NULL,
    `desc_long` text,
    `default_color` text,
    `npcname` text,
    `fx_name` text,
    `fx_bone_name` text,
    `guild_level_permitted` int DEFAULT NULL,
    `housing_script_setpos` int DEFAULT NULL,
    `required_item` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
    `pc_use_type` int DEFAULT NULL,
    `check_type` int DEFAULT NULL,
    `use_cooltime` int DEFAULT NULL,
    `tooltip_type` text,
    `use_delay` int DEFAULT NULL,
    `owner_usecount_per_day` int DEFAULT NULL,
    `pc_use_final_condition` int DEFAULT NULL,
    `reward_use` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
    `erase_value` int DEFAULT NULL,
    `pc_use_count_max` int DEFAULT NULL,
    `request_category` text,
    `reward_final` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
    `housingobj_max_use` int DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `name` (`name`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
COMMIT;