CREATE TABLE `gather_srcs` (
  `id` int(15) NOT NULL,
  `name` varchar(255) NOT NULL,
  `gather_delay` int(1) DEFAULT NULL,
  `normal_rate1` int(10) DEFAULT NULL,
  `harvest_count` int(3) DEFAULT NULL,
  `aerial_adj` int(3) DEFAULT NULL,
  `harvestskill` varchar(20) DEFAULT NULL,
  `success_adj` int(3) DEFAULT NULL,
  `skill_level` int(4) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `source_type` varchar(20) DEFAULT NULL,
  `check_type` int(1) DEFAULT NULL,
  `gather_delay_id` int(1) DEFAULT NULL,
  `source_color` text,
  `source_upper` decimal(8,6) DEFAULT NULL,
  `source_fx` text,
  `material1` varchar(50) DEFAULT NULL,
  `failure_adj` int(4) DEFAULT NULL,
  `captcha_rate` int(4) DEFAULT NULL,
  `motion_name` text,
  `category` varchar(15) DEFAULT NULL,
  `mesh` text,
  `char_level_limit` int(3) DEFAULT NULL,
  `normal_rate2` int(10) DEFAULT NULL,
  `material2` varchar(50) DEFAULT NULL,
  `required_item` varchar(50) DEFAULT NULL,
  `normal_rate3` int(10) DEFAULT NULL,
  `extra_normal_rate3` int(10) DEFAULT NULL,
  `material3` varchar(50) DEFAULT NULL,
  `extra_normal_rate4` int(10) DEFAULT NULL,
  `extra_normal_rate1` int(10) DEFAULT NULL,
  `extra_normal_rate2` int(10) DEFAULT NULL,
  `extra_material1` varchar(50) DEFAULT NULL,
  `erase_value` tinyint(1) DEFAULT NULL,
  `extra_material4` varchar(50) DEFAULT NULL,
  `extra_material3` varchar(50) DEFAULT NULL,
  `extra_material2` varchar(50) DEFAULT NULL,
  `normal_rate5` int(10) DEFAULT NULL,
  `normal_rate4` int(10) DEFAULT NULL,
  `material4` varchar(50) DEFAULT NULL,
  `material5` varchar(50) DEFAULT NULL,
  `normal_rate6` int(10) DEFAULT NULL,
  `material6` varchar(50) DEFAULT NULL,
  `normal_rate7` int(10) DEFAULT NULL,
  `material7` varchar(50) DEFAULT NULL,
  `extra_material7` varchar(50) DEFAULT NULL,
  `extra_material6` varchar(50) DEFAULT NULL,
  `extra_normal_rate7` int(10) DEFAULT NULL,
  `extra_normal_rate5` int(10) DEFAULT NULL,
  `extra_normal_rate6` int(10) DEFAULT NULL,
  `extra_material5` varchar(50) DEFAULT NULL,
  `extra_material8` varchar(50) DEFAULT NULL,
  `extra_normal_rate8` int(10) DEFAULT NULL,
  `normal_rate8` int(10) DEFAULT NULL,
  `material8` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
