CREATE TABLE `skill_base_clients` (
  `id` int(15) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `type` varchar(8) DEFAULT NULL,
  `skill_category` text,
  `ultra_transfer` int(1) DEFAULT NULL,
  `target_slot` text,
  `sub_type` varchar(20) DEFAULT NULL,
  `effect3_hop_b` int(10) DEFAULT NULL,
  `ultra_skill` tinyint(1) DEFAULT NULL,
  `effect3_hop_a` int(3) DEFAULT NULL,
  `effect1_reserved4` varchar(255) DEFAULT NULL,
  `effect1_reserved3` varchar(255) DEFAULT NULL,
  `effect1_reserved5` varchar(255) DEFAULT NULL,
  `activation_attribute` varchar(10) DEFAULT NULL,
  `effect1_reserved2` varchar(255) DEFAULT NULL,
  `effect1_reserved1` varchar(255) DEFAULT NULL,
  `effect1_effectid` int(10) DEFAULT NULL,
  `target_marker_radius` int(1) DEFAULT NULL,
  `effect4_hop_b` int(10) DEFAULT NULL,
  `effect1_basiclv` int(10) DEFAULT NULL,
  `effect4_hop_a` int(10) DEFAULT NULL,
  `desc_long` varchar(255) DEFAULT NULL,
  `delay_id` int(10) DEFAULT NULL,
  `skillicon_name` varchar(255) DEFAULT NULL,
  `cost_charge_weapon` int(10) DEFAULT NULL,
  `effect1_type` varchar(50) DEFAULT NULL,
  `cost_charge_armor` int(10) DEFAULT NULL,
  `first_target` text,
  `cost_end` int(10) DEFAULT NULL,
  `effect1_reserved8` varchar(255) DEFAULT NULL,
  `effect1_reserved7` varchar(255) DEFAULT NULL,
  `effect1_reserved9` varchar(255) DEFAULT NULL,
  `effect1_reserved6` varchar(255) DEFAULT NULL,
  `cost_parameter` varchar(8) DEFAULT NULL,
  `chain_category_priority` varchar(255) DEFAULT NULL,
  `desc_prechain_category_name` varchar(255) DEFAULT NULL,
  `chain_category_level` int(4) DEFAULT NULL,
  `effect1_target_type` text,
  `effect1_noresist` tinyint(1) DEFAULT NULL,
  `penalty_type_succ` tinyint(1) DEFAULT NULL,
  `effect1_reserved13` varchar(255) DEFAULT NULL,
  `effect1_reserved10` varchar(255) DEFAULT NULL,
  `effect3_type` varchar(50) DEFAULT NULL,
  `effect2_cond_preeffect_prob1` int(4) DEFAULT NULL,
  `effect2_cond_preeffect_prob2` int(4) DEFAULT NULL,
  `effect3_effectid` int(10) DEFAULT NULL,
  `effect3_hop_type` text,
  `effect3_noresist` tinyint(1) DEFAULT NULL,
  `effect3_cond_preeffect` text,
  `effect2_reserved13` varchar(255) DEFAULT NULL,
  `effect2_effectid` int(10) DEFAULT NULL,
  `effect3_reserved2` varchar(255) DEFAULT NULL,
  `effect2_noresist` tinyint(1) DEFAULT NULL,
  `effect2_type` varchar(50) DEFAULT NULL,
  `effect3_reserved13` varchar(255) DEFAULT NULL,
  `effect2_checkforchain` tinyint(1) DEFAULT NULL,
  `effect3_cond_preeffect_prob2` int(4) DEFAULT NULL,
  `effect3_cond_preeffect_prob1` int(4) DEFAULT NULL,
  `effect2_reserved2` varchar(255) DEFAULT NULL,
  `effect2_cond_preeffect` text,
  `effect3_checkforchain` tinyint(1) DEFAULT NULL,
  `peace_skill` tinyint(1) DEFAULT NULL,
  `target_stop` tinyint(1) DEFAULT NULL,
  `show_weapon` int(1) DEFAULT NULL,
  `effect2_target_type` text,
  `effect2_reserved1` varchar(255) DEFAULT NULL,
  `effect2_reserved11` varchar(255) DEFAULT NULL,
  `effect2_reserved10` varchar(255) DEFAULT NULL,
  `effect2_critical_prob_mod2` int(4) DEFAULT NULL,
  `move_casting` tinyint(1) DEFAULT NULL,
  `target_species_restriction` text,
  `required_dispel_level` int(3) DEFAULT NULL,
  `required_polearm` tinyint(1) DEFAULT NULL,
  `target_range` text,
  `first_target_valid_distance` int(3) DEFAULT NULL,
  `desc_knight` text,
  `obstacle` int(1) DEFAULT NULL,
  `delay_type` tinyint(1) DEFAULT NULL,
  `effect1_hop_type` text,
  `effect2_remain2` int(10) DEFAULT NULL,
  `required_mace` tinyint(1) DEFAULT NULL,
  `required_staff` tinyint(1) DEFAULT NULL,
  `effect2_remain1` int(10) DEFAULT NULL,
  `effect2_reserved6` varchar(255) DEFAULT NULL,
  `chain_category_name` text,
  `required_sword` tinyint(1) DEFAULT NULL,
  `target_relation_restriction` text,
  `auto_attack` text,
  `desc_long_2nd` text,
  `effect1_critical_prob_mod2` int(10) DEFAULT NULL,
  `hostile_type` text,
  `cancel_rate` int(10) DEFAULT NULL,
  `effect2_hop_type` text,
  `delay_time` int(10) DEFAULT NULL,
  `required_dagger` tinyint(1) DEFAULT NULL,
  `required_2hsword` tinyint(1) DEFAULT NULL,
  `add_wpn_range` tinyint(1) DEFAULT NULL,
  `dispel_category` text,
  `effect1_reserved11` varchar(255) DEFAULT NULL,
  `chain_skill_prob2` int(4) DEFAULT NULL,
  `motion_name` text,
  `effect1_reserved15` varchar(255) DEFAULT NULL,
  `effect2_hop_b` int(10) DEFAULT NULL,
  `desc_abnormal` text,
  `effect2_hop_a` int(10) DEFAULT NULL,
  `effect2_basiclv` int(10) DEFAULT NULL,
  `counter_skill` text,
  `required_leftweapon` text,
  `effect2_acc_mod2` int(10) DEFAULT NULL,
  `effect1_hop_a` int(10) DEFAULT NULL,
  `effect1_hop_b` int(10) DEFAULT NULL,
  `instant_skill` tinyint(1) DEFAULT NULL,
  `motion_play_speed` int(4) DEFAULT NULL,
  `effect1_reserved12` varchar(255) DEFAULT NULL,
  `chain_time` int(10) DEFAULT NULL,
  `effect2_reserved8` varchar(255) DEFAULT NULL,
  `effect2_reserved_cond1_prob2` int(10) DEFAULT NULL,
  `effect2_reserved7` varchar(255) DEFAULT NULL,
  `effect2_reserved_cond1_prob1` int(10) DEFAULT NULL,
  `prechain_category_name` text,
  `effect2_reserved_cond1` text,
  `effect1_remain1` int(10) DEFAULT NULL,
  `effect1_remain2` int(10) DEFAULT NULL,
  `self_flying_restriction` text,
  `effect3_target_type` text,
  `effect2_reserved4` varchar(255) DEFAULT NULL,
  `change_stance` text,
  `effect2_reserved3` varchar(255) DEFAULT NULL,
  `effect3_reserved1` varchar(255) DEFAULT NULL,
  `cost_dp` int(4) DEFAULT NULL,
  `effect1_reserved16` varchar(255) DEFAULT NULL,
  `effect1_reserved17` varchar(255) DEFAULT NULL,
  `effect1_reserved14` varchar(255) DEFAULT NULL,
  `cost_end_lv` int(4) DEFAULT NULL,
  `effect1_hidemsg` int(1) DEFAULT NULL,
  `casting_delay` int(10) DEFAULT NULL,
  `effect3_reserved6` varchar(255) DEFAULT NULL,
  `effect3_reserved11` varchar(255) DEFAULT NULL,
  `effect3_reserved10` varchar(255) DEFAULT NULL,
  `effect3_remain2` int(10) DEFAULT NULL,
  `effect3_remain1` int(10) DEFAULT NULL,
  `target_valid_status1` text,
  `target_valid_status2` text,
  `effect2_reserved12` varchar(255) DEFAULT NULL,
  `motion_mode` text,
  `no_jump_cancel` tinyint(1) DEFAULT NULL,
  `target_range_opt1` int(3) DEFAULT NULL,
  `target_range_opt3` int(3) DEFAULT NULL,
  `target_maxcount` int(3) DEFAULT NULL,
  `target_range_area_type` text,
  `penalty_skill_succ` text,
  `effect1_reserved18` varchar(255) DEFAULT NULL,
  `target_flying_restriction` text,
  `pvp_damage_ratio` int(3) DEFAULT NULL,
  `effect3_critical_prob_mod2` int(4) DEFAULT NULL,
  `effect3_basiclv` int(4) DEFAULT NULL,
  `effect1_reserved_cond1_prob2` int(10) DEFAULT NULL,
  `effect1_reserved_cond1_prob1` text,
  `effect1_reserved_cond1` text,
  `effect4_cond_preeffect_prob2` int(4) DEFAULT NULL,
  `effect4_cond_preeffect_prob1` int(4) DEFAULT NULL,
  `effect4_reserved2` varchar(255) DEFAULT NULL,
  `effect4_reserved1` varchar(255) DEFAULT NULL,
  `effect4_target_type` text,
  `effect4_checkforchain` tinyint(1) DEFAULT NULL,
  `effect4_cond_preeffect` text,
  `effect4_reserved10` varchar(255) DEFAULT NULL,
  `effect4_reserved13` varchar(255) DEFAULT NULL,
  `effect4_reserved11` varchar(255) DEFAULT NULL,
  `effect4_type` varchar(50) DEFAULT NULL,
  `effect4_effectid` int(10) DEFAULT NULL,
  `effect4_noresist` tinyint(1) DEFAULT NULL,
  `splash` tinyint(1) DEFAULT NULL,
  `effect4_reserved6` varchar(255) DEFAULT NULL,
  `effect4_remain2` int(10) DEFAULT NULL,
  `effect4_remain1` int(10) DEFAULT NULL,
  `effect4_basiclv` int(4) DEFAULT NULL,
  `revision_distance` int(3) DEFAULT NULL,
  `effect1_checktime` int(10) DEFAULT NULL,
  `effect2_randomtime` int(10) DEFAULT NULL,
  `effect2_checktime` int(10) DEFAULT NULL,
  `effect2_reserved9` varchar(255) DEFAULT NULL,
  `effect1_acc_mod2` int(10) DEFAULT NULL,
  `effect3_reserved9` varchar(255) DEFAULT NULL,
  `effect3_reserved3` varchar(255) DEFAULT NULL,
  `effect3_reserved4` varchar(255) DEFAULT NULL,
  `remove_at_fly_end` tinyint(1) DEFAULT NULL,
  `effect4_reserved3` varchar(255) DEFAULT NULL,
  `effect4_reserved7` varchar(255) DEFAULT NULL,
  `effect4_reserved4` varchar(255) DEFAULT NULL,
  `effect4_reserved14` varchar(255) DEFAULT NULL,
  `max_maintain_count` int(1) DEFAULT NULL,
  `target_slot_level` int(4) DEFAULT NULL,
  `effect3_reserved_cond1` text,
  `effect3_reserved7` varchar(255) DEFAULT NULL,
  `effect3_reserved8` varchar(255) DEFAULT NULL,
  `effect4_critical_prob_mod2` int(10) DEFAULT NULL,
  `effect3_reserved_cond1_prob2` int(10) DEFAULT NULL,
  `effect3_reserved_cond1_prob1` int(10) DEFAULT NULL,
  `effect1_randomtime` int(10) DEFAULT NULL,
  `nouse_combat_state` tinyint(1) DEFAULT NULL,
  `required_bow` tinyint(1) DEFAULT NULL,
  `component_expendable` tinyint(1) DEFAULT NULL,
  `component_count` int(3) DEFAULT NULL,
  `component` text,
  `use_arrow` tinyint(1) DEFAULT NULL,
  `use_arrow_count` int(1) DEFAULT NULL,
  `effect3_reserved5` varchar(255) DEFAULT NULL,
  `effect2_reserved5` varchar(255) DEFAULT NULL,
  `cast_voice` text,
  `effect2_reserved16` varchar(255) DEFAULT NULL,
  `effect4_reserved16` varchar(255) DEFAULT NULL,
  `effect3_reserved16` varchar(255) DEFAULT NULL,
  `effect2_reserved17` varchar(255) DEFAULT NULL,
  `effect2_reserved15` varchar(255) DEFAULT NULL,
  `effect2_reserved14` varchar(255) DEFAULT NULL,
  `effect1_acc_mod1` int(10) DEFAULT NULL,
  `effect3_randomtime` int(10) DEFAULT NULL,
  `chain_skill_prob1` int(10) DEFAULT NULL,
  `effect2_cond_status_prob2` int(10) DEFAULT NULL,
  `effect2_cond_status_prob1` int(10) DEFAULT NULL,
  `effect2_cond_status` text,
  `clone` int(1) DEFAULT NULL,
  `cost_time` int(10) DEFAULT NULL,
  `cost_toggle` int(4) DEFAULT NULL,
  `effect4_reserved8` varchar(255) DEFAULT NULL,
  `effect4_reserved_cond1` text,
  `effect4_reserved_cond1_prob1` int(10) DEFAULT NULL,
  `effect4_reserved_cond1_prob2` int(10) DEFAULT NULL,
  `cost_checktime_lv` int(1) DEFAULT NULL,
  `cost_checktime` int(3) DEFAULT NULL,
  `cost_checktime_parameter` text,
  `effect2_reserved18` varchar(255) DEFAULT NULL,
  `cost_start` int(5) DEFAULT NULL,
  `pvp_remain_time_ratio` int(3) DEFAULT NULL,
  `effect2_hidemsg` tinyint(1) DEFAULT NULL,
  `effect1_critical_add_dmg_mod2` int(10) DEFAULT NULL,
  `effect4_hop_type` text,
  `effect3_acc_mod2` int(10) DEFAULT NULL,
  `effect3_checktime` int(10) DEFAULT NULL,
  `required_dp_lv` tinyint(1) DEFAULT NULL,
  `no_save_on_logout` tinyint(1) DEFAULT NULL,
  `required_book` tinyint(1) DEFAULT NULL,
  `required_orb` tinyint(1) DEFAULT NULL,
  `effect3_hidemsg` tinyint(1) DEFAULT NULL,
  `effect4_hidemsg` tinyint(1) DEFAULT NULL,
  `target_range_opt2` int(10) DEFAULT NULL,
  `target_range_opt4` text,
  `pvp_skill_cancel_bonus` int(10) DEFAULT NULL,
  `target_valid_status3` text,
  `target_valid_status4` text,
  `target_valid_status5` text,
  `effect3_reserved14` varchar(255) DEFAULT NULL,
  `effect3_reserved12` varchar(255) DEFAULT NULL,
  `effect2_acc_mod1` int(10) DEFAULT NULL,
  `effect2_cond_attack_dir_prob2` int(10) DEFAULT NULL,
  `effect2_cond_attack_dir_prob1` int(10) DEFAULT NULL,
  `effect2_cond_attack_dir` tinyint(1) DEFAULT NULL,
  `effect2_critical_add_dmg_mod2` int(10) DEFAULT NULL,
  `effect2_critical_add_dmg_mod1` int(10) DEFAULT NULL,
  `effect2_critical_prob_mod1` int(10) DEFAULT NULL,
  `effect1_critical_add_dmg_mod1` int(10) DEFAULT NULL,
  `effect1_critical_prob_mod1` int(10) DEFAULT NULL,
  `no_remove_at_die` tinyint(1) DEFAULT NULL,
  `effect4_reserved12` varchar(255) DEFAULT NULL,
  `effect4_reserved18` varchar(255) DEFAULT NULL,
  `effect4_reserved17` varchar(255) DEFAULT NULL,
  `effect4_reserved15` varchar(255) DEFAULT NULL,
  `effect3_reserved15` varchar(255) DEFAULT NULL,
  `effect3_reserved17` varchar(255) DEFAULT NULL,
  `effect3_reserved18` varchar(255) DEFAULT NULL,
  `effect3_reserved_cond2_prob1` int(10) DEFAULT NULL,
  `effect3_reserved_cond2` text,
  `effect3_reserved_cond2_prob2` int(10) DEFAULT NULL,
  `conflict_id` int(10) DEFAULT NULL,
  `effect4_reserved9` varchar(255) DEFAULT NULL,
  `effect4_checktime` int(10) DEFAULT NULL,
  `effect2_cond_race` text,
  `effect2_cond_race_prob2` int(10) DEFAULT NULL,
  `effect2_cond_race_prob1` int(10) DEFAULT NULL,
  `nonchained_delay_time` int(10) DEFAULT NULL,
  `prechain_skillname` text,
  `broadcast_use_message` tinyint(1) DEFAULT NULL,
  `allow_use_form_category` text,
  `effect4_reserved5` varchar(255) DEFAULT NULL,
  `stc_desc` text,
  `effect3_cond_attack_dir_prob2` int(10) DEFAULT NULL,
  `effect3_cond_attack_dir_prob1` int(10) DEFAULT NULL,
  `effect3_cond_attack_dir` tinyint(1) DEFAULT NULL,
  `effect3_cond_status_prob2` int(10) DEFAULT NULL,
  `effect3_cond_status` text,
  `effect3_cond_status_prob1` int(10) DEFAULT NULL,
  `effect4_cond_status` text,
  `effect4_cond_status_prob1` int(10) DEFAULT NULL,
  `effect4_cond_status_prob2` int(10) DEFAULT NULL,
  `effect3_cond_race_prob2` int(10) DEFAULT NULL,
  `effect1_reserved_cond2_prob1` int(10) DEFAULT NULL,
  `effect1_reserved_cond2` text,
  `effect1_reserved_cond2_prob2` int(10) DEFAULT NULL,
  `max_skill_point` int(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
